# Generated by Django 4.0.7 on 2025-04-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_baseuser_delete_date_baseuser_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
